/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package main

const auditTemplate = `<!-- Code generated by hack/cnpatroni/audit. DO NOT EDIT. -->
<!-- Regenerate with: go -C hack/cnpatroni/audit run . doc -->

# HA authority audit

Generated by ` + "`hack/cnpatroni/audit`" + ` from ` + "`{{.Rules}}`" + `, the classification file beside it, and the
tree as it stands. The document carries no build stamp on purpose: a timestamp or a commit hash would
change on every commit and turn the drift check into noise, so this file changes only when the audit
actually changes. Provenance for the numbers is the baseline record below.

This is the audit required by specification section 9.1. It inventories every reachable code path in
this repository that can influence PostgreSQL role or process lifecycle, and records what
CloudNativePatroni intends to do about each one.

## How this document is maintained

This file is generated and intentionally not committed. Editing it by hand is pointless: the next
` + "`doc`" + ` run overwrites it. The authority-audit workflow regenerates both documents on every run,
fails if rendering fails, and uploads them together as the ` + "`cnpatroni-authority-audit`" + ` artifact.
To produce local copies from the repository root, run
` + "`go -C hack/cnpatroni/audit run . doc`" + `.

The judgement a scanner cannot produce, which is what to do about a symbol, lives in
` + "`hack/cnpatroni/audit/policy/authority-classification.yaml`" + `. The scanner cross-checks that file in
both directions: every hit it finds must be classified, and every classification must still name a
symbol that exists. A code path that appears during an upstream merge and has no classification
fails the check by name, which is the mechanism specification section 9.3 asks for.

The prose in the fork-feasibility section below is a template fragment,
` + "`hack/cnpatroni/audit/policy/authority-audit-narrative.md`" + `, into which the measured numbers are
substituted at render time. Two numbers in that section are exceptions, because they describe git
history rather than the current tree; they are marked as hand-measured and carry the command that
produced them.

## Scope of the scan

| Measure | Value |
|---|---:|
| Packages type-checked | {{.Packages}} |
| Go files inspected | {{.Files}} |
| Findings | {{.Findings}} |
| Classified symbols | {{.Entries}} |
| Mapped responsibilities | {{.Responsibilities}} |
| Allowlist entries | {{.AllowEntries}} |

Test files and generated files are excluded, comments are structurally absent because the scanner
parses without them, and method calls are resolved through the type checker so that a method sharing
a name with a guarded one, such as ` + "`(*http.Server).Shutdown`" + `, does not match.

## Summary

### Classification counts

| Classification | Symbols |
|---|---:|
{{range .ByClass}}| {{.Name}} | {{.Count}} |
{{end}}
### Destination counts

| Destination | Symbols |
|---|---:|
{{range .ByDest}}| {{.Name}} | {{.Count}} |
{{end}}
### Rule coverage

Severity ` + "`forbidden`" + ` marks an operation specification section 7.4 forbids; those hits are counted in
the baseline. Severity ` + "`inventory`" + ` marks a path that must be triaged but is not itself a violation.
Severity ` + "`observe`" + ` covers the remaining specification section 9.1 search terms, which are counted so
that coverage is visible but are never gated.

| Rule | Severity | Specification | Hits | Symbols | Files |
|---|---|---|---:|---:|---:|
{{range .ByRule}}| ` + "`{{.ID}}`" + ` | {{.Severity}} | {{if .Spec}}{{.Spec}}{{else}}-{{end}} | {{.Hits}} | {{.Symbols}} | {{.Files}} |
{{end}}
### Forbidden-call baseline

The baseline is the ratchet. On day one this repository is unmodified CloudNativePG and is full of
forbidden calls, so a gate that failed on any of them would be red from the first commit and would be
switched off within a week. The recorded totals may fall and must never rise.

Recorded from commit ` + "`{{.Baseline.GeneratedFrom}}`" + ` at {{.Baseline.GeneratedAt}}.

| Measure | Value |
|---|---:|
| Forbidden hits recorded | {{.Baseline.Total}} |
| Buckets, keyed by rule and enclosing symbol | {{len .Baseline.Buckets}} |

Buckets are keyed by ` + "`(rule, enclosing symbol)`" + ` rather than by file and line. Line numbers churn on
every upstream merge, and a file-keyed baseline would let a merge add a brand new forbidden call
inside a file that is already listed. A new function is always a new bucket, so that case fails.

## Fork feasibility

{{template "narrative" .}}

## Inventory by package

Each row is one classified symbol. ` + "`Rules`" + ` names the scanner rules that matched it; a symbol with no
rule listed is classified pre-emptively because a neighbouring symbol pulled it in.

{{range .ByPackage}}### {{.Package}}

| Symbol | Path | Rules | Class | Destination | Rationale |
|---|---|---|---|---|---|
{{range .Entries}}| ` + "`{{.Short}}`" + ` | ` + "`{{.Path}}`" + ` | {{if .Rules}}` + "`{{.Rules}}`" + `{{else}}-{{end}} | {{.Class}} | {{.DestProse}} | {{.Rationale}} |
{{end}}
{{end}}
## Instance-manager responsibility map

The second requirement of specification section 9.1, which is a statement about responsibilities
rather than about symbols, is rendered separately as
[the responsibility map](responsibility-map.md). It is generated from the same data file and is
anchored on real symbols, so an upstream change that deletes an anchor flags the responsibility row
as stale. The local command above always creates both ignored files, and continuous integration
uploads them in the same artifact, so this relative link remains intact.

## The container startup contract, and why it has no test yet

Design B pairs this audit with a third guardrail: a check that the database container's startup path
cannot become a supervisor. That guardrail is **not implemented in M0**, and the reason is worth
stating plainly rather than hiding behind a green tick.

There is nothing to inspect. This repository contains no entrypoint script, no image directory, and
no database-image Dockerfile; the only ` + "`Dockerfile`" + ` present builds the operator and its entry point is
already exec form. A checker written against those files today would assert nothing and would report
success, which is worse than no checker: it would be cited as evidence.

The contract itself is recorded here so that the M1 change that adds the Patroni image has something
to be checked against:

| # | Contract |
|---|---|
| C1 | The startup path ends in ` + "`exec`" + `. After setup, process 1 is Patroni, or a transparent init whose only child is Patroni and which exits when Patroni exits. |
| C2 | No supervisor. No loop that restarts Patroni or PostgreSQL, no supervision suite, no backgrounding followed by a wait. Restarting the container is the kubelet's job. |
| C3 | Signals reach Patroni. A termination signal to process 1 is delivered to Patroni, nothing traps it away, and the container exits within its termination grace period. |
| C4 | A Patroni exit terminates the container, for any exit status, and the container's status is Patroni's. |
| C5 | No PostgreSQL process survives the container. |
| C6 | The startup path never starts PostgreSQL itself. |
| C7 | The probes address Patroni's REST endpoint rather than the instance manager's status port. |

C1 in particular cannot be checked by searching for the word ` + "`exec`" + `: it is a statement about the last
statement on every control-flow path, so the M1 checker needs a shell parser rather than a pattern
match. C3, C4 and C5 are statements about a running container and need a container to run.

The M0 substitute is the classification of ` + "`pkg/specs.createPostgresContainers`" + ` in the inventory above.
That symbol is where the database container's command and probes are chosen, so the audit will report
it the moment the M1 change touches it, and the reviewer is pointed at this contract.

## Known limitations

1. A static audit is not a proof, and specification section 9.3 says so. Reflection, templating, and
   any path through an interface whose implementation is chosen at run time can evade the type-aware
   engine. The mitigation is the chaos suite in M3, not more static analysis.
2. The audit does not scan Patroni. Patroni is Python and lives outside this repository; the
   container contract covers the boundary, and Patroni's own behaviour is upstream's.
3. A baseline keyed by symbol notices a second forbidden call added to an already-listed function
   only through the bucket count, not as a distinct finding. That is the intended sensitivity.
4. The scanner requires the tree to type-check. During a difficult upstream merge it is unavailable
   until the build is fixed, which is reported as exit code 2 so that it is never mistaken for
   compliance.

## Reproduction

` + "```bash" + `
cd hack/cnpatroni/audit

go run . scan                       # print the inventory
go run . check                      # the gate: exit 1 policy, 2 tool, 3 hygiene
go run . baseline --write           # re-record the ratchet, human-invoked only
go run . doc                        # regenerate this document
go test ./...                       # the scanner's own tests
` + "```" + `
`

const responsibilityTemplate = `<!-- Code generated by hack/cnpatroni/audit. DO NOT EDIT. -->
<!-- Regenerate with: go -C hack/cnpatroni/audit run . doc -->

# Instance-manager responsibility map

Generated by ` + "`hack/cnpatroni/audit`" + ` from the same classification file as
[the authority audit](authority-audit.md).

This file and the authority audit are intentionally not committed. Produce both local copies with
` + "`go -C hack/cnpatroni/audit run . doc`" + `, or obtain them together from the
` + "`cnpatroni-authority-audit`" + ` workflow artifact.

This is the second requirement of specification section 9.1: every responsibility the CloudNativePG
instance manager holds today, mapped to where it goes in CloudNativePatroni.

A responsibility is a statement about behaviour, not about a symbol, so it cannot be generated from
the code. It is kept honest instead by ` + "`anchors`" + `: each row lists the symbols that implement it, and
the audit check reports the row as stale when an anchor no longer exists. A human then has to confirm
that the responsibility moved rather than quietly vanished.

The destination vocabulary is specification section 9.1's:
Patroni container, finite init, cnpatroni-agent, operator, disabled.

## The map

{{range .ResponsibilityRows}}### {{.Responsibility}}

**Destination:** {{dest .Dest}} · **Reviewed:** {{.ReviewedAt}} · **Owner:** {{.Owner}}

{{.Rationale}}

Anchors:

{{range .Anchors}}- ` + "`{{.}}`" + `
{{end}}
{{end}}
## Reading this map

"disabled" means the behaviour has no successor in CloudNativePatroni, because Patroni performs it.
"finite init" means the work must run once and exit, and must not become a supervisor. "cnpatroni-agent"
means the work stays inside the Pod but must survive Patroni restarting PostgreSQL underneath it, and
must ask Patroni which instance is the leader rather than reading the CloudNativePG cluster status.
"operator" means the work stays in the control plane and becomes an observation of Patroni rather
than a decision about PostgreSQL.
`
